FROM golang:1.22.5 AS builder

WORKDIR /app

COPY src/movie-event-consumer ./movie-event-consumer
COPY src/events ./events
COPY src/utils ./utils

WORKDIR /app/movie-event-consumer
RUN go mod download

WORKDIR /app/events
RUN go mod download

WORKDIR /app/utils
RUN go mod download

WORKDIR /app/movie-event-consumer/cmd
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/movieeventconsumer .


FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/movieeventconsumer .

CMD ["./movieeventconsumer"]
