FROM golang:1.22.5 AS builder

WORKDIR /app

COPY src/actor-api ./actor-api
COPY src/grpc ./grpc
COPY src/events ./events
COPY src/utils ./utils

WORKDIR /app/actor-api
RUN go mod download

WORKDIR /app/grpc
RUN go mod download

WORKDIR /app/events
RUN go mod download

WORKDIR /app/utils
RUN go mod download

WORKDIR /app/actor-api/cmd/api
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/actorapi .


FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/actorapi .

CMD ["./actorapi"]
