FROM golang:1.22.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o user-grpc ./cmd/grpc

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/user-grpc .

# Set environment variables (if needed)
# ENV PORT=8080

# Expose the port the app runs on
EXPOSE 6002

# Command to run the executable
CMD ["./actor-api"]
